# Generated by Django 5.1.4 on 2025-01-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('updated_in', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('in_stock', models.IntegerField(default=0)),
                ('production_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('purchased_in', models.DateField()),
                ('condition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='Material.condition')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.materialtype')),
            ],
        ),
    ]
