# Generated by Django 4.2.17 on 2025-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0002_material_created_in_material_updated_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='updated_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='updated_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
