# Generated by Django 4.2.17 on 2025-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='updated_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
