# Generated by Django 4.2.17 on 2025-01-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_cashflow_created_in_cashflow_updated_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='name',
            field=models.CharField(default='Total', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='updated_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowtype',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flowtype',
            name='updated_in',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
