# Generated by Django 4.2.17 on 2025-01-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_event_invite_date_event_reminder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invite_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='send_invite',
        ),
        migrations.RemoveField(
            model_name='event',
            name='send_reminder',
        ),
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
