# Generated by Django 4.2.17 on 2025-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_event_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
