# Generated by Django 5.2.3 on 2025-06-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_athlete_delete_athletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='category',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')]),
        ),
    ]
